CREATE TABLE CLIENTE (
  NOME VARCHAR(250) NOT NULL,
  CPF VARCHAR(14) NOT NULL,
  TELEFONE VARCHAR(12) NOT NULL,
  EMAIL VARCHAR(250) NOT NULL,
  CONSTRAINT CLIENTE_PK PRIMARY KEY
  (
    CPF
  )
  ENABLE
);

CREATE TABLE VEICULO (
  PLACA VARCHAR(12) NOT NULL,
  MODELO VARCHAR(250) NOT NULL,
  FABRICANTE VARCHAR(250) NOT NULL,
  TIPO VARCHAR(250) NOT NULL,
  ANO NUMBER NOT NULL,
  COR VARCHAR(250) NOT NULL,
  ID_CLIENTE VARCHAR(14) NOT NULL,
  CONSTRAINT VEICULO_PK PRIMARY KEY
  (
    PLACA
  )
  ENABLE
);

CREATE TABLE FUNCIONARIO (
  NOME VARCHAR(250) NOT NULL,
  CODIGO VARCHAR(10) NOT NULL,
  SENHA VARCHAR(100) NOT NULL,
  TELEFONE VARCHAR(12) NOT NULL,
  EMAIL VARCHAR(250) NOT NULL,
  CONSTRAINT FUNCIONARIO_PK PRIMARY KEY
  (
    CODIGO
  )
  ENABLE
);

CREATE TABLE MATERIAL (
  ID_MATERIAL NUMBER NOT NULL,
  DESCRICAO VARCHAR(250) NOT NULL,
  CODIGO NUMBER NOT NULL,
  FABRICANTE VARCHAR(250) NOT NULL,
  CLASSIFICACAO VARCHAR(250) NOT NULL,
  VALORUNITARIO NUMBER NOT NULL,
  CONSTRAINT MATERIAL_PK PRIMARY KEY
  (
    ID_MATERIAL
  )
  ENABLE
);

CREATE TABLE ORDEMSERVICO (
  ID_ORDEMSERVICO NUMBER NOT NULL,
  DATAENTRADA DATE NOT NULL,
  DATASERVICOINICIO DATE NOT NULL,
  DATASERVICOFIM DATE NOT NULL,
  VEICULO VARCHAR(12) NOT NULL,
  FUNCIONARIO VARCHAR(10) NOT NULL,
  VALORTOTAL NUMBER NOT NULL,
  VALORMAODEOBRA NUMBER NOT NULL,
  QUILOMETRAGEM  NUMBER NOT NULL,
  OBS VARCHAR(500) NOT NULL,
  STATUS VARCHAR(250) NOT NULL,
  VALIDADE DATE NOT NULL,
  CONSTRAINT ORDEMSERVICO_PK PRIMARY KEY
  (
    ID_ORDEMSERVICO
  )
  ENABLE
);

CREATE TABLE ITEMSERVICO (
  ID_ITEMSERVICO NUMBER NOT NULL,
  ID_MATERIAL NUMBER NOT NULL,
  ID_ORDEMSERVICO NUMBER NOT NULL,
  QTD NUMBER NOT NULL,
  CONSTRAINT ITEMSERVICO_PK PRIMARY KEY
  (
    ID_ITEMSERVICO
  )
  ENABLE
);

ALTER TABLE VEICULO ADD CONSTRAINT FK_CLIENTE
  FOREIGN KEY(ID_CLIENTE) REFERENCES
  CLIENTE(CPF);
  
ALTER TABLE ORDEMSERVICO ADD CONSTRAINT FK_VEICULO
  FOREIGN KEY(VEICULO) REFERENCES
  VEICULO(PLACA);
  
ALTER TABLE ORDEMSERVICO ADD CONSTRAINT FK_FUNCIONARIO 
  FOREIGN KEY(FUNCIONARIO) REFERENCES
  FUNCIONARIO(CODIGO); 
  
ALTER TABLE ITEMSERVICO ADD CONSTRAINT FK_MATERIAL
  FOREIGN KEY(ID_MATERIAL) REFERENCES
  MATERIAL(ID_MATERIAL);
  
ALTER TABLE ITEMSERVICO ADD CONSTRAINT FK_ORDEMSERVICO
  FOREIGN KEY(ID_ORDEMSERVICO) REFERENCES
  ORDEMSERVICO(ID_ORDEMSERVICO); 
  
CREATE SEQUENCE S_ID_MATERIAL INCREMENT BY 1 START WITH 1 MINVALUE 1;

CREATE SEQUENCE S_ID_ORDEMSERVICO INCREMENT BY 1 START WITH 1 MINVALUE 1;

CREATE SEQUENCE S_ID_ITEMSERVICO INCREMENT BY 1 START WITH 1 MINVALUE 1;

CREATE OR REPLACE TRIGGER T_ID_MATERIAL 
BEFORE INSERT ON MATERIAL 
  FOR EACH ROW
BEGIN
    IF INSERTING THEN
      IF :NEW.ID_MATERIAL IS NULL THEN 
        SELECT S_ID_MATERIAL.NEXTVAL INTO :NEW.ID_MATERIAL FROM DUAL;
      END IF;
    END IF;
END;

CREATE OR REPLACE TRIGGER T_ID_ORDEMSERVICO 
BEFORE INSERT ON ORDEMSERVICO 
  FOR EACH ROW
BEGIN
    IF INSERTING THEN
      IF :NEW.ID_ORDEMSERVICO IS NULL THEN 
        SELECT S_ID_ORDEMSERVICO.NEXTVAL INTO :NEW.ID_ORDEMSERVICO FROM DUAL;
      END IF;
    END IF;
END;

CREATE OR REPLACE TRIGGER T_ID_ITEMSERVICO 
BEFORE INSERT ON ITEMSERVICO  
  FOR EACH ROW
BEGIN
    IF INSERTING THEN
      IF :NEW.ID_ITEMSERVICO IS NULL THEN 
        SELECT S_ID_ITEMSERVICO.NEXTVAL INTO :NEW.ID_ITEMSERVICO FROM DUAL;
      END IF;
    END IF;
END; 